## Deliverable 2. Create a Customer Travel Destinations Map.

In [1]:
# Dependencies and Setup
import pandas as pd
import requests
import gmaps

# Import API key
from config import g_key

# Configure gmaps API key
gmaps.configure(api_key=g_key)

In [2]:
# 1. Import the WeatherPy_database.csv file. 
city_data_df = pd.read_csv("WeatherPy_database.csv")
city_data_df.head(10)

,City_ID,City,Country,Lat,Lng,Max Temp,Humidity,Cloudiness,Wind Speed,Current Description
0,0,Punta Arenas,CL,-53.15,-70.92,44.60,75,40,9.17,scattered clouds
1,1,Klaksvik,FO,62.23,-6.59,51.80,93,59,16.11,light rain
2,2,Xuddur,SO,4.12,43.89,73.44,65,95,20.58,overcast clouds
3,3,Ushuaia,AR,-54.80,-68.30,39.20,86,75,11.41,light intensity drizzle
4,4,Mocuba,MZ,-16.84,36.99,63.16,74,0,4.05,clear sky
5,5,Bourg-En-Bresse,FR,46.17,5.17,64.00,68,73,1.01,broken clouds
6,6,Butaritari,KI,3.07,172.79,82.81,66,21,1.48,few clouds
7,7,Airai,TL,-8.93,125.41,58.55,69,16,3.40,few clouds
8,8,Goderich,CA,43.75,-81.72,81.00,66,32,23.49,scattered clouds
9,9,Castro,BR,-24.79,-50.01,67.77,70,0,5.14,clear sky

In [3]:
# 2. Prompt the user to enter minimum and maximum temperature criteria in °F.
min_temp = float(input("What is the minimum temperature in °F you would like for your trip? "))
max_temp = float(input("What is the maximum temperature in °F you would like for your trip? "))

What is the minimum temperature in °F you would like for your trip? 74
What is the maximum temperature in °F you would like for your trip? 89

In [5]:
# 3. Filter the city_data_df DataFrame using the input statements to create a new DataFrame using the loc method.
preferred_cities_df = city_data_df.loc[(city_data_df["Max Temp"] <= max_temp) & \
                                       (city_data_df["Max Temp"] >= min_temp)]
preferred_cities_df

,City_ID,City,Country,Lat,Lng,Max Temp,Humidity,Cloudiness,Wind Speed,Current Description
6,6,Butaritari,KI,3.07,172.79,82.81,66,21,1.48,few clouds
8,8,Goderich,CA,43.75,-81.72,81.00,66,32,23.49,scattered clouds
12,12,Ribeira Grande,PT,38.52,-28.70,75.20,73,40,2.24,scattered clouds
18,18,Puerto Ayora,EC,-0.74,-90.35,75.20,60,20,17.22,few clouds
23,23,Yalta,UA,44.50,34.17,75.43,68,24,2.62,few clouds
...,...,...,...,...,...,...,...,...,...,...
688,688,Puerto Escondido,MX,15.85,-97.07,87.80,58,75,4.70,broken clouds
691,691,Muli,MV,2.92,73.57,82.58,78,33,17.74,scattered clouds
692,692,Manta,EC,-0.95,-80.73,77.00,78,20,14.99,few clouds
699,699,Durango,MX,24.83,-104.83,75.60,48,99,7.63,overcast clouds
701,701,Olinda,BR,-8.01,-34.86,78.80,69,40,11.41,scattered clouds

In [6]:
# 4a. Determine if there are any empty rows.
preferred_cities_df.count()

City_ID                242
City                   242
Country                242
Lat                    242
Lng                    242
Max Temp               242
Humidity               242
Cloudiness             242
Wind Speed             242
Current Description    242
dtype: int64

In [ ]:
# 4b. Drop any empty rows and create a new DataFrame that doesn’t have empty rows.
#preferred_cities_df = city_data_df.loc[(city_data_df["Max Temp"] == max_temp)

In [7]:
# 5a. Create DataFrame called hotel_df to store hotel names along with city, country, max temp, and coordinates.
hotel_df = preferred_cities_df[["City", "Country", "Max Temp", "Current Description", "Lat", "Lng"]].copy()

# 5b. Create a new column "Hotel Name"
hotel_df["Hotel Name"] = ""
hotel_df.head(10)

,City,Country,Max Temp,Current Description,Lat,Lng,Hotel Name
6,Butaritari,KI,82.81,few clouds,3.07,172.79,
8,Goderich,CA,81.00,scattered clouds,43.75,-81.72,
12,Ribeira Grande,PT,75.20,scattered clouds,38.52,-28.70,
18,Puerto Ayora,EC,75.20,few clouds,-0.74,-90.35,
23,Yalta,UA,75.43,few clouds,44.50,34.17,
26,Bethel,US,81.00,clear sky,41.37,-73.41,
30,Victoria,HK,84.00,broken clouds,22.29,114.16,
33,Sinnamary,GF,81.88,clear sky,5.38,-52.95,
34,Locri,IT,75.99,scattered clouds,38.24,16.26,
35,Lufilufi,WS,87.80,broken clouds,-13.87,-171.60,

In [16]:
# 6a. Set parameters to search for hotels with 5000 meters.
params = {
    "radius": 5000,
    "type": "lodging",
    "key": g_key
}

# 6b. Iterate through the hotel DataFrame.
for index, row in hotel_df.iterrows():

    # 6c. Get latitude and longitude from DataFrame
    lat = row["Lat"]
    lng = row["Lng"]
    params["location"] = f"{lat},{lng}"
    # params[]
    
    # 6d. Set up the base URL for the Google Directions API to get JSON data.
    # base_url = "https://maps.googleapis.com/maps/api/directions/nearbysearch/json"
    base_url = "https://maps.googleapis.com/maps/api/place/nearbysearch/json"

    # 6e. Make request and retrieve the JSON data from the search. 
    hotels = requests.get(base_url, params=params).json()
    
    # 6f. Get the first hotel from the results and store the name, if a hotel isn't found skip the city.
    try:
        hotel_df.loc[index, "Hotel Name"] = hotels["results"][0]["name"]
    except (IndexError):
        print("Hotel not found... skipping.")

Hotel not found... skipping.
Hotel not found... skipping.
Hotel not found... skipping.
Hotel not found... skipping.
Hotel not found... skipping.
Hotel not found... skipping.
Hotel not found... skipping.
Hotel not found... skipping.
Hotel not found... skipping.
Hotel not found... skipping.
Hotel not found... skipping.
Hotel not found... skipping.
Hotel not found... skipping.
Hotel not found... skipping.
Hotel not found... skipping.
Hotel not found... skipping.
Hotel not found... skipping.
Hotel not found... skipping.
Hotel not found... skipping.

In [23]:
hotel_df.head(12)

,City,Country,Max Temp,Current Description,Lat,Lng,Hotel Name
6,Butaritari,KI,82.81,few clouds,3.07,172.79,Isles Sunset Lodge
8,Goderich,CA,81.00,scattered clouds,43.75,-81.72,Harmony Inn
12,Ribeira Grande,PT,75.20,scattered clouds,38.52,-28.70,Quinta da Meia Eira
18,Puerto Ayora,EC,75.20,few clouds,-0.74,-90.35,Finch Bay Galapagos Hotel
23,Yalta,UA,75.43,few clouds,44.50,34.17,Yalta-Inturist
26,Bethel,US,81.00,clear sky,41.37,-73.41,Courtyard by Marriott Danbury
30,Victoria,HK,84.00,broken clouds,22.29,114.16,Mini Hotel Central
33,Sinnamary,GF,81.88,clear sky,5.38,-52.95,ALETHEIA Appartement Sinnamary
34,Locri,IT,75.99,scattered clouds,38.24,16.26,Grand Hotel President
35,Lufilufi,WS,87.80,broken clouds,-13.87,-171.60,Leuaina Beach Resort and Spa
36,Hithadhoo,MV,81.72,few clouds,-0.60,73.08,Scoop Guest House
37,Ocara,BR,77.92,overcast clouds,-4.49,-38.60,Pousada familiar

In [19]:
# 7. Drop the rows where there is no Hotel Name.  -- search for hotel at google places, sort through, drop rows without a hotel after the loop... 

# city_data_df["Lat"] >= 0

# hotel_df = hotel_df

In [20]:
# 8a. Create the output File (CSV)
output_data_file = "WeatherPy_vacation.csv"

# 8b. Export the City_Data into a csv
hotel_df.to_csv(output_data_file, index_label="City_ID")

In [27]:
# 9. Using the template add city name, the country code, the weather description and maximum temperature for the city.
info_box_template = """
<dl>
<dt>Hotel Name</dt><dd>{Hotel Name}</dd>
<dt>City</dt><dd>{City}</dd>
<dt>Country</dt><dd>{Country}</dd>
<dt>Current Weather</dt><dd>{Current Description}</dd>
<dt>Max Temp</dt><dd>{Max Temp} °F</dd>
</dl>
"""

# 10a. Get the data from each row and add it to the formatting template and store the data in a list.
hotel_info = [info_box_template.format(**row) for index, row in hotel_df.iterrows()]

# 10b. Get the latitude and longitude from each row and store in a new DataFrame.
locations = hotel_df[["Lat", "Lng"]]

In [28]:
# 11a. Add a marker layer for each city to the map. 
locations = hotel_df[["Lat", "Lng"]]
max_temp = hotel_df["Max Temp"]
fig = gmaps.figure(center=(30.0, 31.0), zoom_level=1.5)
#heat_layer = gmaps.heatmap_layer(locations, weights=max_temp,dissipating=False,
#             max_intensity=300, point_radius=4)
marker_layer = gmaps.marker_layer(locations, info_box_content=hotel_info)
#fig.add_layer(heat_layer)
fig.add_layer(marker_layer)


# 11b. Display the figure
fig

Figure(layout=FigureLayout(height='420px'))